apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","sleep 3600"]
    # - "/bin/bash"
    # - "-c"
    # - "sleep 3600"
  # nodeSelector:
  #   disktype: ssd
  

## 标签, -L -l区别
## kubectl get pods -L app
# NAME       READY   STATUS    RESTARTS   AGE   APP
# pod-demo   2/2     Running   0          14m   myapp
# 
## kubectl get pods -l app
# NAME       READY   STATUS    RESTARTS   AGE   
# pod-demo   2/2     Running   0          14m   

## kubectl get pods --show-labels
## kubectl get pods -L app,run
## kubectl get pods -l app --show-labels
## kubectl label pods pod-demo release=canary
## kubectl label pods pod-demo release=stable ##已有标签，再次打标，不加--overwrite会报错
# error: 'release' already has a value (canary), and --overwrite is false
## kubectl label pods pod-demo release=stable --overwrite
## kubectl get pods -l release,app  ## 筛选含有release，app标签的pod
## 
## kubectl get pods -l release=stable,app=myapp  ##指定标签条件并查看
##
## kubectl get pods -L app
# NAME       READY   STATUS    RESTARTS   AGE   APP
# pod-demo   2/2     Running   0          14m   myapp
## kubectl get pods -l app --show-labels
# NAME       READY   STATUS    RESTARTS   AGE   LABELS
# pod-demo   2/2     Running   0          14m   app=myapp,release=stable,tier=frontend

## kubectl get pods -l release!=canary  ## 不等值关系查找
## kubectl get pods -l "release in (canary,beta,alpha)"  ## 集合关系查找
## kubectl get pods -l "release notin (canary,beta,alpha)"

## 许多资源支持内嵌字段定义其使用的标签选择器：
##  matchlabels: 直接给定键值
##  matchExpressions: 基于给定的表达式来定义使用标签选择器