apiVersion: v1
kind: Service
metadata:
  name: tomcat-jmx-demo-svc
  labels:
    k8s-app: tomcat-jmx
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 1234
    targetPort: 1234
    name: prom
  selector:
    k8s-app: tomcat-jmx
#   type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-jmx-demo
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: tomcat-jmx
        type: java
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '1234'
    spec:
      containers:
      - name: tomcat-jmx-pod-demo
        image: tomcat:jmx1234
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_AGENT_PORT
          value: "1234"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1"
          limits:
            memory: "1024Mi"
            cpu: "1"