kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
  #annotations:
    #storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/cephfs
parameters:
    monitors: 192.168.2.148:6789,192.168.2.149:6789,192.168.2.150:6789
    adminId: admin
    adminSecretName: cephfs-admin-secret
    adminSecretNamespace: "kube-system"
    #userId: cephfs
    #userSecretName: cephfs-secret
    claimRoot: /pvc-volumes
