apiVersion: v1  ##直接挂载的方式让Pod服务使用 cephfs：
kind: Pod
metadata:
  name: cephfs2
spec:
  containers:
  - name: cephfs-rw
    image: busybox
    command:
    - sleep
    - "36000"
    volumeMounts: ##容器内部需要挂载的目录
    - mountPath: "/var/log"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 192.168.2.148:6789
      - 192.168.2.149:6789
      - 192.168.2.150:6789
      user: cephfs
      secretRef:
        name: cephfs-secret
      readOnly: false
      path: /direct-ceph-pod  ##cephfs默认挂载端需要提前mkdir该目录
