apiVersion: v1
kind: Secret
metadata:
  name: cephfs-admin-secret
  namespace: kube-system
data:
  # ceph auth get-key client.admin| base64
  key: QVFDZnNPUmROL1FsSmhBQWdvZlpSM1hCZWI2bkhEU1RFMXZPYmc9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: cephfs-secret
  namespace: kube-system
data:
  # ceph auth get-or-create client.cephfs mon 'allow *' mds 'allow *' osd 'allow *'
  # ceph auth get-key client.cephfs|base64
  key: QVFCNngzbGVGRWhKS1JBQUFDMUc2M1oxNHVReDQ2bFg3d2hTcVE9PQ==
