apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: ceph-rbd
  annotations:
     storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.2.148:6789,192.168.2.149:6789,192.168.2.150:6789
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: kube-system
  #pool: rbd
  pool: kube
  userId: kube
  userSecretName: ceph-secret
#  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
