apiVersion: v1
kind: Pod
metadata:
  name: ceph-pod2
spec:
  containers:
  - name: ceph-busybox2
    image: busybox
    command: ["sleep", "60000"]
    volumeMounts:
    - name: ceph-vol2
      mountPath: /usr/share/busybox
      readOnly: false
  volumes:
  - name: ceph-vol2
    persistentVolumeClaim:
      claimName: ceph-claim22
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-claim22
spec:
  accessModes:  
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
