apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin-secret
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  key: QVFDZnNPUmROL1FsSmhBQWdvZlpSM1hCZWI2bkhEU1RFMXZPYmc9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  key: QVFDVzMrMWRPQVEzRnhBQXpUa2xKL1JFenEyNWNPMWU0SFBKWGc9PQ==
